apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${ name }
spec:
  schedule: "${ cron_schedule_string }"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysqldump
              image: ${ mysqldump_image }
              imagePullPolicy: Always
              env:
                - name: AWS_ASSUME_ARN
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: role_arn
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: backup
                      key: access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: backup
                      key: secret_access_key
                - name: BACKUP_S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: s3_bucket
                - name: MYSQL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: host
                - name: MYSQL_USERNAME
                  value: "root"
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${ mysql_secret_name }
                      key: ${ mysql_secret_pass_key }
                - name: ACTION
                  value: "backup"
          restartPolicy: OnFailure
